baseurl                 = "https://thedreamersclub.github.io/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "The Dreamers' Club"
theme                   = "sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-126279941-1"             # Tracking code, eg. "UA-111111111-1"

# build options
buildDrafts             = false # builds drafts
enableEmoji             = true # enables the use of emoji codes
publishDir              = "thedreamersclub"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 NZST"
    favicon             = "/sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Copyright 2018 The Dreamers Club"

# Metadata
    description         = "Ideas, dreams and secret projects."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "Events"

# [[params.mainMenu]]
#     link = "/gallery"
#     text = "gallery"

[[params.mainMenu]]
    link = "/about"
    text = "The Dreamers' Club"